name: Python application test with Github Actions
on: 
  push:
    branches: [ test1,test2,main]
  pull_request:
    branches: [ main ]
    types: [ closed ]
 
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.10
    - name: Install dependencies
      run: |
        make install
    - name: Black Formatter
      run: |
        make format
    - name: Lint
      run: |
        make lint
